swagger: "2.0"
info:
  title: "Bookstore API"
  description: "A bookstore API project"
  termsOfService: "Demo"
  contact:
    name: "Thomas Hochbichler"
    url: "http://hochbichler.at/bookstore"
    email: "thomas@hochbichler.at"
  version: "0.0.1"
host: "localhost:8080"
basePath: "/v0"
schemes:
- http
securityDefinitions:
  basicAuth:
    type: basic
security:
  - basicAuth: []
paths:
  /books:
    get:
      tags:
      - "book"
      operationId: "filterAllBooks"
      description: "Returns all books"
      produces:
      - application/json
      security:
        - basicAuth: []
      responses:
        '200':
          description: "Returns a list of books"
          schema:
            type: array
            items:
              $ref: '#/definitions/Book'
        '401':
          $ref: "#/responses/UnauthorizedError"
    post:
      tags:
      - "book"
      operationId: "addNewBook"
      description: "Adds a new book"
      produces:
      - application/json
      consumes:
      - application/json
      security:
        - basicAuth: []
      parameters:
      - in: "body"
        name: "body"
        description: "A JSON book objects"
        required: true
        schema:
          $ref: '#/definitions/Book'
      responses:
        '201':
          description: "Returns the added book"
          schema:
            $ref: '#/definitions/Book'
        '405':
          description: "Invalid input"
        '401':
          $ref: "#/responses/UnauthorizedError"
definitions:
  Book:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      description:
        type: string
        pattern: '^\d{3}-\d{2}-\d{4}$'
    required:
    - id
    - name
    example:
    - id: 100
      name: Book title
      description: This is the book description
responses:
  UnauthorizedError:
    description: Authentication information is missing or invalid
    headers:
      WWW_Authenticate:
        type: string