openapi: 3.0.0
info:
  title: Bookstore
  description: My demo bookstore
  version: 0.0.1

servers: 
  - url: http://localhost:8080/v1
    description: Local development environment
  - url: https://bookstore.hochbichler.at/v1
    description: Production environment
    
paths:
  /books:
    get:
      summary: Return all books
      description: Retrieve all books from the store
      responses:
        '200':
            description: if OK, returns a list of books
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Book'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralError'
components:
  schemas:
    Book:
      properties:
        id:
          type: integer
        name:
          type: string
      required:
        - id
        - name
    GeneralError:
      properties:
        code:
          type: string
        description:
          type: string
      required:
        - code
        - description